config/routes.rb
DaysPickerRailsExamples::Application.routes.draw do

  root 'days_picker#index'

  
  
  resources :days_picker, only: [:index,:create] do 
    collection do 
    end
  end
  
  get 'by_years' => 'days_picker#by_year'
  get 'by_year_and_months' => 'days_picker#by_year_and_month'
  

end

app/models/days_picker.rb
class DaysPicker
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :year, :type,:month
  
  @@types = ['weekdays', 'sundays', 'mondays', 'tuesdays', 'wednesdays', 'thursdays', 'fridays', 'saturdays']
  validates_presence_of :year
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  

  def self.fetch_for(year)
  	hsh = HashWithIndifferentAccess.new
  	hsh[:weekdays] = Weekdays.by_year(year).count.to_s
  	hsh[:sundays] = Sundays.by_year(year).count.to_s
  	hsh[:mondays] = Mondays.by_year(year).count.to_s
  	hsh[:tuesdays] = Tuesdays.by_year(year).count.to_s
  	hsh[:wednesdays] = Wednesdays.by_year(year).count.to_s
  	hsh[:thursdays] = Thursdays.by_year(year).count.to_s
  	hsh[:fridays] = Fridays.by_year(year).count.to_s
  	hsh[:saturdays] = Saturdays.by_year(year).count.to_s
  	hsh
  end
  
  def self.types
    @@types.collect(&:capitalize)
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/days_picker_controller.rb
class DaysPickerController < ApplicationController

	def index
	
	end


	def by_year
		@type = params[:type]
		@year = params[:year].to_i
		@dates = eval(@type).by_year(@year)
		@count = @dates.count
		@data = {count: @count, type: @type, year: @year, dates: @dates}
		respond_to do |format|
           format.js 
	   end
	end

	def by_year_and_month
		@type = params[:type]
		@year = params[:year]
		@month = params[:date][:month]
		@dates = eval(@type).by_year_and_month(@year.to_i,@month.to_i)
		@formatted_dates = @dates.collect {|i| i.strftime('%d-%b-%Y')}.join(', ')
		@count = @dates.count
		@data = {count: @count, type: @type, year: @year, dates: @formatted_dates,month: @month}
		respond_to do |format|
           format.js 
	   end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_picker_helper.rb
module DaysPickerHelper
end

app/views/days_picker/_about.html.erb
<div class='panel' >
	<h4 class="subheader">This Site holds examples on the Usage of <a href='https://github.com/ankit8898/days_picker' target='_blank' >Days Picker</a> Library which a wrapper on top of <a href='http://ruby-doc.org/stdlib-2.0.0/libdoc/date/rdoc/Date.html' target='_blank' >Ruby Date Class </a>Created by <a href='http://www.linkedin.com/pub/ankit-gupta/25/205/254' target='_blank'>Ankit Gupta.</a></h4>
 
 <h5 class='subheader'>Easily find Sundays, Mondays,Tuesdays ... and Weekdays of any Month and Year with single line of Ruby code <i class="fa fa-coffee"></i></h5>
</div>
<a href='https://github.com/ankit8898' target='_blank' class='button small right'>Follow Ankit on Github <i class="fa fa-github-alt"></i></a>
<br/>
<br/>
<br/>

app/views/days_picker/_by_year.html.erb
<h1 class="subheader">Example 2 <i class="fa fa-bookmark"></i></h1>
<%= form_tag by_years_path, method: :get, class: 'custom', remote: true do  %>
  <div class="row">
      <div class="large-6 columns">
      <label for="customDropdown1">Select a Day Type</label>
      <%= select_tag :type, options_for_select(DaysPicker.types, 'weekdays'), id: 'customDropdown1' %>
    </div>
    <div class="large-6 columns">
      <label for="customDropdown1">Select a Year</label>
      <%= select_tag :year, options_for_select(2009..2050, Date.today.year.to_s), id: 'customDropdown1' %>
    </div>
  </div>
  <div class="row">
     <div class="large-12 columns">
  <%= submit_tag 'Get Dates',class: "medium button success" %>
</div>
</div>
<% end %>

app/views/days_picker/_by_year_and_month.html.erb
<h1 class="subheader">Example 1 <i class="fa fa-bookmark"></i></h1>
<%= form_tag by_year_and_months_path, method: :get, class: 'custom', remote: true do  %>
<div class="row">
  <div class="large-4 columns">
    <label for="customDropdown1">Select a Day Type</label>
    <%= select_tag :type, options_for_select(DaysPicker.types, 'weekdays'), id: 'customDropdown1' %>  
  </div>
  <div class="large-4 columns">
    <label for="customDropdown1">Select a Month</label>
    <%= select_month(Date.today,:field_name => 'month',class: 'medium', id: 'customDropdown1') %>  
  </div>
  <div class="large-4 columns">
    <label for="customDropdown1">Select a Year</label>
    <%= select_tag :year, options_for_select(2009..2050, Date.today.year.to_s), id: 'customDropdown1' %>
  </div>
  
</div>

<div class="row">
 <div class="large-12 columns">
  <%= submit_tag 'Get Dates',class: "medium button success" %>
</div>
</div>
<% end %>

app/views/days_picker/_output.html.erb
<% if defined? by_month %>
<div class="panel callout">
<h3> There are <%= days %> <%= type %> in <%= year %>. </h3>
</div>
<% else defined? by_month_and_year %>
<div class="panel callout">
	<h3> There are <%= days %> <%= type %> in <%= Date::MONTHNAMES[month.to_i] %> - <%= year %>. </h3>
</div>
<span data-tooltip class="has-tip" title='<%= dates %>'>View dates</span>
<%end%>



<a class="close-reveal-modal">&#215;</a>

app/views/days_picker/by_year.js.erb
$('#myModal').html("<%= escape_javascript(render partial: 'output', locals: {type: @data[:type], year: @data[:year], days: @data[:count],by_month: true}) %>")
$('#myModal').foundation('reveal', 'open');

app/views/days_picker/by_year_and_month.js.erb
$('#myModal').html("<%= escape_javascript(render partial: 'output', locals: {type: @data[:type], year: @data[:year], month: @data[:month],days: @data[:count],dates: @data[:dates]}, by_year_and_month: true) %>")
$('#myModal').foundation('reveal', 'open');

app/views/days_picker/index.html.erb
<%= render 'about' %>

<div id="myModal" class="xlarge reveal-modal"></div>

<%= render 'by_year_and_month' %>

<%= render 'by_year' %>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
<a href="https://github.com/ankit8898/days_picker_example" target='_blank'><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub"></a>
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#"> Days Picker Example</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Days Picker Example" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <%= render 'layouts/nav' %>
    <div class="row extramargin">
  <div class="large-12 columns"> <%= yield %></div>
    &nbsp;
  </div>
</div>

   

    
    <%= javascript_include_tag "application" %>
  </body>
</html>